-- MySQL Script generated by MySQL Workbench
-- Thu Sep 23 14:06:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema todo-list
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema todo-list
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todo-list` DEFAULT CHARACTER SET utf8 ;
USE `todo-list` ;

-- -----------------------------------------------------
-- Table `todo-list`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo-list`.`item` (
  `item-id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(150) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`item-id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
